name: Check
on: [push, pull_request]
jobs:
  statics:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - run: |
          make install-tools
          make check
